### ISSUE TITLE
by chance did you record your prompt process as a video?

### ISSUE THREAD

**Issue by pleabargain** [remghoost/webp-png-converter#1]
By chance did you record your prompt process as a video?
If yes, will you post? I for one would be interested in seeing the evolution /tweaking of your prompts.

thanks

**Comment by remghoost** [comment]
I did not record a video. Hadn't thought to do that...

I have the entire prompting session in a pastebin though.
Here's the link to it. 
https://pastebin.com/g8FSdwEw

**Comment by pleabargain** [comment]
Many thanks for the link!
